### ISSUE TITLE
Invalid library found in xxx/Arduino/libraries/EpoxyDuino: no headers files (.h) found in xxx/Arduino/libraries/EpoxyDuino

### ISSUE THREAD

**Issue by sylvaneau** [bxparks/EpoxyDuino#62]
Hi,

I followed the setup instructions and the EpoxyDuino library causes a small warning when loading Arduino IDE:

`Invalid library found in xxx/Arduino/libraries/EpoxyDuino: no headers files (.h) found in xxx/Arduino/libraries/EpoxyDuino`

I know it is due to the fact this library isn't really an actual Arduino library but it's a bit anoying to see this warning every time you startup the IDE :-)

After some testing it seems that adding an empty `EpoxyDuino.h` fixes the problem.

An alternative would be not to put this project inside the library folder to prevent the IDE to try to scan it.

**Comment by bxparks** [comment]
That's a good idea. Done.
I never got these warning messages because as a creator of many Arduino libraries, my Arduino IDE libraries folder structure had to be different than most end-users. It was easiest to use a collection of symlinks from the Arduino libraries folder out to elsewhere where my git repos are located, and it turned out that my symlinks didn't need to include the EpoxyDuino directory.
